"""Create comment table.

Revision ID: 461756447c4f
Revises: e6bae18373c3
Create Date: 2020-04-16 12:33:33.874180

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "461756447c4f"
down_revision = "e6bae18373c3"
branch_labels = None
depends_on = None


def upgrade():
    """Pushes changes into the database."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("depth", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "lineage",
            postgresql.ARRAY(postgresql.UUID(as_uuid=True)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["comment.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_refresh_updated_at_trigger("comment")
    op.create_refresh_depth_and_lineage_trigger("comment")
    # ### end Alembic commands ###


def downgrade():
    """Reverts changes performed by upgrade()."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_refresh_depth_and_lineage_trigger("comment")
    op.drop_refresh_updated_at_trigger("comment")
    op.drop_table("comment")
    # ### end Alembic commands ###
